### PR TITLE
Replace CertifiedTransaction

### PR DESCRIPTION
**Pull request by Scofield626**
A quick hack of not using `CertifiedTransaction`.

The main changes are following:

1. Replace `CertifiedTransaction` via `sui_types::transaction::Transaction` which has `EmptySignInfo`
2. Move `certify_transaction` call into the beginning of `E::execute`
3. Rename the original `Transaction<E>` trait to `RemoraTransaction<E>` given the introduction of sui_types's `Transaction`
4. Ignore the shared-transaction load generation. Plan to handle it later.

### CODE REVIEW

**Comment by asonnino** [comment]
Do we need to move certify_transaction in the executor? Why not removing it entirely (to remain closer to the next iteration of Sui)?

**Review by asonnino — COMMENTED** [review]
We may need to unify the notion of RemoraTransaction and TransactionWithTimestamp. But this can be done later

**Comment by asonnino** [comment]
Also let’s remove all dead code since we won’t go back to executing certificates ?

**Comment by Scofield626** [comment]
> Do we need to move certify_transaction in the executor? Why not removing it entirely (to remain closer to the next iteration of Sui)?

Hey @asonnino, I tried to figure out which APIs I should use upon Transaction instead of Certificate. I think I need to replace check_certificate_input via [check_transaction_input](https://github.com/Scofield626/sui/blob/0c99cacf03bfd054af50f558b8eff4fb63358872/crates/sui-transaction-checks/src/lib.rs#L69) to turn `InputObjects` type into `CheckedInputObjects` so that it can feed to `execute_transaction_to_effects`. But it has some fields I didn't see before, i.e., `receiving_objects` and `metrics`

**Review by asonnino — APPROVED** [review]

**Pull request merged**
